# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [1]:
import numpy as np

### Задание 1

Создать 12x12 единичную матрицу (с единицами по диагонали)

In [2]:
np.eye(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Задание 2 *

Создать 9x9 матрицу и заполнить её в шахматном порядке

In [10]:
matrix = np.zeros((9, 9), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]]


### Задание 3

Отсортировать произвольный вектор в порядке возрастания

In [11]:
np.random.seed(42)
vector = np.random.random(10)
np.sort(vector)

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.60111501, 0.70807258, 0.73199394, 0.86617615, 0.95071431])

### Задание 4

Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [17]:
np.random.seed(42)
fourth_array = np.random.randint(3, 5,(8, 3))
#print(fourth_array)
rows_with_all_fours = np.all(fourth_array == 4, axis=1)
print(rows_with_all_fours)

[False False False False False False False False]


### Задание 5

Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

In [23]:
i=np.zeros(6)
i[-1]=1
print(i)

[0. 0. 0. 0. 0. 1.]


### Задание 6

Укажите индекс 9 элемента в массиве 2х3х2

In [27]:
np.unravel_index(9, np.zeros((2, 3, 2)).shape)

(1, 1, 1)